### ISSUE TITLE
dataset not found error while running YOLO v8 object detection script

### ISSUE THREAD

**Issue by SriPrarabdha** [roboflow/notebooks#41] opened 2023-01-15 19:19 UTC
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

YOLO v8 Notebook - 
https://github.com/roboflow/notebooks/blob/main/notebooks/train-yolov8-object-detection-on-custom-dataset.ipynb

### Bug

After collecting the football dataset successfully when I am running the custom training, it is throwing a 'dataset not found' error in both Kaggle and colab

<img width="842" alt="error1" src="https://user-images.githubusercontent.com/89463301/212562019-1aefa2ec-49fe-4308-99c0-4027029a7c98.png">

### Environment

- Google Colab and Kaggle
- Python 3.10

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment] 2023-01-15 23:17
Hi, @SriPrarabdha 👋🏻! I just pushed some changes that should solve the problem. It would be awsome if you could take a look and test if you still experience the issues.

**Comment by IAMHAADICOOL** [comment] 2023-01-17 11:39
I am also having the same error

**Comment by SkalskiP** [comment] 2023-01-17 12:52
Hi, @IAMHAADICOOL 👋🏻! Could you send me a link to Google Colab that you are using?

**Comment by IAMHAADICOOL** [comment] 2023-01-17 13:07
Because I haven't been working on Google Collab

**Comment by IAMHAADICOOL** [comment] 2023-01-17 13:08
Or I can send that Roboflow dataset link, I know you asked not to share
with anyone, but it's you, so it's alright, right?

**Comment by IAMHAADICOOL** [comment] 2023-01-17 13:08
And thanks for replying, I really am stuck so bad and can't understand what
to do

**Comment by SkalskiP** [comment] 2023-01-17 14:56
@IAMHAADICOOL  I don't need a dataset. Just Jupyter Notebook. Send it over to piotr@roboflow.com

**Comment by SkalskiP** [comment] 2023-01-18 10:33
Looks like we managed to solve that issue. I'm closing it.

**Closed by SkalskiP** 2023-01-18 10:33 UTC
Labels: bug

**Comment by IAMHAADICOOL** [comment] 2023-01-20 21:53
The issue is not resolving, can you please help? I need to submit a project and it's deadline, will be highly grateful if you replied

**Comment by IAMHAADICOOL** [comment] 2023-01-20 21:54
![image](https://user-images.githubusercontent.com/99788862/213812129-a3ad4163-aadc-4a57-b84d-98116ba85364.png)

**Comment by SkalskiP** [comment] 2023-01-23 15:22
Hi, @IAMHAADICOOL! 👋🏻 Sorry I was not working over the weekend. Are you sure you have `data.yaml` under `D:\dataet\data.yaml`?

**Comment by SkalskiP** [comment] 2023-01-23 15:23
Also, are you using our notebook?

**Comment by IAMHAADICOOL** [comment] 2023-01-23 16:20
Yes yes

**Comment by SkalskiP** [comment] 2023-01-23 18:20
@IAMHAADICOOL can you send me that notebook?
