### ISSUE TITLE
Exclude classes

### ISSUE THREAD

**Issue by st43r** [roboflow/notebooks#130] opened 2023-05-24 17:08 UTC
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Description

Hey Piotr, could you please me? 
i want to try make object detection on pretrained YoloNasL model  but i need to exclude some classes for example class person

///
model = models.get(MODEL_ARCH, pretrained_weights="coco").to(DEVICE)

image = cv2.imread(SOURCE_IMAGE_PATH)
result = list(model.predict(image, conf=0.35))[0]
///

how can i set some properties of model like class_names at give array with class names to that property?
i checked all properties but didnt find out where or how i can exclude some yolo classes

i would be extremely grateful if you try to help

thanks in advance!!

environment is google colab

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment] 2023-05-31 14:47
Duplicate of https://github.com/roboflow/notebooks/discussions/131

**Closed by SkalskiP** 2023-05-31 14:47 UTC
Labels: enhancement
