### ISSUE TITLE
from thop import profile

### ISSUE THREAD

**Issue by SuryaPrakash0201** [roboflow/notebooks#150] opened 2023-06-17 18:05 UTC
### Search before asking

- [X] I have searched the Roboflow Notebooks [issues](https://github.com/roboflow-ai/notebooks/issues) and found no similar bug report.

### Notebook name

https://colab.research.google.com/github/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8.ipynb#scrollTo=lAFba4GkombF

### Bug

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-8-db369db504f9>](https://localhost:8080/#) in <cell line: 23>()
     21 
     22 
---> 23 import yolox
     24 print("yolox.__version__:", yolox.__version__)

2 frames
[/content/ByteTrack/yolox/__init__.py](https://localhost:8080/#) in <module>
      2 # -*- coding:utf-8 -*-
      3 
----> 4 from .utils import configure_module
      5 
      6 configure_module()

[/content/ByteTrack/yolox/utils/__init__.py](https://localhost:8080/#) in <module>
     12 from .lr_scheduler import LRScheduler
     13 from .metric import *
---> 14 from .model_utils import *
     15 from .setup_env import *
     16 from .visualize import *

[/content/ByteTrack/yolox/utils/model_utils.py](https://localhost:8080/#) in <module>
      5 import torch
      6 import torch.nn as nn
----> 7 from thop import profile
      8 
      9 from copy import deepcopy

ModuleNotFoundError: No module named 'thop'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

### Environment

Colab

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by SkalskiP** [comment] 2023-06-19 04:11
Hi @SuryaPrakash0201 👋🏻 ! Thanks a lot for bringing that problem to my attention. Looks like a duplicate of #106.

**Closed by SkalskiP** 2023-06-19 04:11 UTC
Labels: bug, duplicate
