### ISSUE TITLE
Can anyone help me on this one please?

### ISSUE THREAD

**Issue by mohdsaqibxa** [roboflow/notebooks#174] opened 2023-07-28 06:40 UTC
Can anyone help me on this one please?

_Originally posted by @mohdsaqibxa in https://github.com/roboflow/notebooks/issues/169#issuecomment-1655116215_

**Comment by SkalskiP** [comment] 2023-07-28 10:26
Closing. Duplicate of https://github.com/roboflow/notebooks/issues/169.

**Closed by SkalskiP** 2023-07-28 10:26 UTC
Labels: duplicate
